https://github.com/rnshah9/mayhem-dbcc
mayhemheroes/SmallerC pull request #1
Opened 2022-05-15 23:49 UTC by rnshah9

2022-06-07 23:22 UTC, xansec requested changes

2022-06-07 23:22 UTC, xansec commented on Dockerfile
> +ADD . /SmallerC
Please use stages.

2022-06-07 23:22 UTC, xansec commented on Mayhemfile
> +project: rnshah9/mayhem-smallerc
Please use generic project name and correct filepath directive.

2022-06-07 23:24 UTC, xansec commented
Unrelated, but why is this named `dbcc`?

2022-06-08 01:09 UTC, rnshah9 commented
Not sure what happened there, must have made a typo

2022-06-08 17:29 UTC, xansec commented
LGTM

2022-06-08 17:29 UTC, merged